version: '3'

services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${UBOTPGUSR}
      - POSTGRES_PASSWORD=${UBOTPGPWD}
      - POSTGRES_DB=${UBOTPGDB}
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    expose:
      - 5432
  bot:
    restart: always
    build: .
    depends_on:
      - postgres
    volumes:
      - "logs/:/code/logs"
    command: bash -c "curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh | bash -s -h postgres -p 5432 && pipenv run start"

volumes:
  pgdata:
  logs: